import React from 'react';
import Header from '@/components/ui/header';
import Sidebar from '@/components/ui/Sidebar';
import '@/styles/globals.css';

import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Tribal Health',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <div className='flex h-screen'>
          <Sidebar /> {/* Sidebar on the left */}
          <div className='flex-1 flex flex-col'>
            <Header />
            <main className='flex-1 p-4'>
              {children} {/* Content area for the dashboard */}
            </main>
          </div>
        </div>
      </body>
    </html>
  );
}
